import { Table, Relationship, Project } from '../types'
import { DDLOptions, IDDLGenerator } from './types'
import { MySQLDDLGenerator } from './MySQLGenerator'
import { PostgreSQLDDLGenerator } from './PostgreSQLGenerator'
import { SQLiteDDLGenerator } from './SQLiteGenerator'
import { SQLServerDDLGenerator } from './SQLServerGenerator'
import { OracleDDLGenerator } from './OracleGenerator'

export class DDLGeneratorFactory {
  static getGenerator(databaseType: DDLOptions['databaseType']): IDDLGenerator {
    switch (databaseType) {
      case 'MYSQL':
        return new MySQLDDLGenerator()
      case 'POSTGRESQL':
        return new PostgreSQLDDLGenerator()
      case 'SQLITE':
        return new SQLiteDDLGenerator()
      case 'SQLSERVER':
        return new SQLServerDDLGenerator()
      case 'ORACLE':
        return new OracleDDLGenerator()
      default:
        return new MySQLDDLGenerator()
    }
  }

  static generateCompleteSQL(
    project: Project,
    tables: Table[],
    relationships: Relationship[],
    options: Partial<DDLOptions> = {}
  ): string {
    const defaultOptions: DDLOptions = {
      databaseType: project.databaseType as any,
      includeComments: true,
      formatSql: true,
      uppercaseKeywords: true,
      includeDropTable: false,
      ...options
    }

    const generator = this.getGenerator(defaultOptions.databaseType)
    const tableMap = new Map<string, Table>()
    tables.forEach(t => tableMap.set(t.id, t))

    const lines: string[] = []
    lines.push(`-- Database: ${project.name}`)
    lines.push(`-- Exported at: ${new Date().toISOString()}`)
    lines.push(`-- Database type: ${defaultOptions.databaseType}`)
    lines.push('')

    if (project.description) {
      lines.push(`-- ${project.description}`)
      lines.push('')
    }

    lines.push(`-- Generated by DataRelationshipDesigner`)
    lines.push('')

    tables.forEach(table => {
      lines.push(generator.generateCreateTable(table, relationships, tableMap, defaultOptions))
      lines.push('')
    })

    return lines.join('\n')
  }
}
